### ISSUE TITLE
The requested resource /api/users/login was not found on this server

### ISSUE THREAD

**Issue by bci24** [rosoftdeveloper/appseed#3]
Run the server on port 3000 and when testing with postman i get that error.

The route is defined in the api.php I don`t know why not found it.

**Comment by rosoftdeveloper** [comment]
Hello, 
Please tell me the backend you are trying to use. [ flask, laravel, or express ]

**Comment by bci24** [comment]
laravel

**Comment by rosoftdeveloper** [comment]
P.S. for LIVE support, you may join us on [Discord](https://discord.gg/fZC6hup)
We are there almost 24/7.

**Comment by rosoftdeveloper** [comment]
Ok, let me double check the Laravel kit.

**Comment by rosoftdeveloper** [comment]
Hello, 
Something is not ok in your env. I've just updated the README. Steps are:
- `cd appseed/starter-laravel`
- `create/edit .env` file to match your DB credentials
-  `php artisan key:generate` 
- `php artisan migrate:fresh --seed`
- Start the server from the public directory
   `php -S localhost:3000` 

![image](https://user-images.githubusercontent.com/15912497/57293023-1fc2a500-70cc-11e9-8fb9-7992fa252dc6.png)

Don't forget to set the proper header:
![image](https://user-images.githubusercontent.com/15912497/57293051-3668fc00-70cc-11e9-8a3c-b4e138dd21b3.png)

Let me know if you still have issues. 
P.S. In case you're familiar with Javascript,  the Express starter is enhanced to use SQLite, + registration..

**Comment by bci24** [comment]
the steps are correct ... the same problem persist.

If i start the server using:  php artisan serve (localhost:8000) it works. 

It`s not working for me with (php -S localhost:3000). I am using Ubuntu 18.04.2 LTS

**Comment by rosoftdeveloper** [comment]
and you can access localhost:8000/api/users/login ?

**Comment by bci24** [comment]
yes
![argon-vue](https://user-images.githubusercontent.com/49674076/57294378-28b57580-70d0-11e9-9246-8975a575bf93.png)

**Comment by rosoftdeveloper** [comment]
Just tested with `php artisan`. It works in my env. `Win10 x64`,  `PHP 7.2.16`
A small note:
- `php -S localhost:3000` should be executed from public directory: : `appseed/starter-laravel/public` 
- `php artisan serve` should be executed from project root: `appseed/starter-laravel` 

![image](https://user-images.githubusercontent.com/15912497/57294528-9cf01900-70d0-11e9-8ce8-4a824e3d53a8.png)

![image](https://user-images.githubusercontent.com/15912497/57294543-ae392580-70d0-11e9-8545-ce33763e7857.png)

**Comment by rosoftdeveloper** [comment]
https://stackoverflow.com/questions/17990820/set-port-for-php-artisan-php-serve
Your patch:

`php artisan serve --port=3000`
 
Cheers!
I will close this issue

**Comment by bci24** [comment]
that was the problem. Starting the server (php -S localhost:3000) from public now it works :)

**Comment by rosoftdeveloper** [comment]
Glad to help. 
See u
